title: Mike Griffin
author: Mike Griffin
url: "https://mikegriffin.ie"
permalink: /blog/:year:month:day-:title
repository: "mgriffin/mikegriffin"
exclude: 
  - Rakefile
  - README.md
  - _drafts
  - Gemfile
  - Gemfile.lock
  - script
  - test
  - vendor

plugins:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "results"
    values:
      layout: "result"
      category: "result"

collections:
  results:
    output: true
